{
  "hash": "dd9256591e83cef74bb96e0dd33346fd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Evaluating California's Sustainable Groundwater Management Act\"\ndescription: \"Using segmented regression to analyze groundwater level trends before and after SGMA implementation\"\nauthor: \"Richard Montes Lemus\"\ndate: \"2024-12-05\"\ncategories: [water resources, policy analysis, R, regression]\nimage: \"groundwater.png\"\ndraft: false\n---\n\n[Link to Github Repository](https://github.com/richardmonteslemus/Cal_SGMA) This repository contains code, file structures, and references for the following California Sustainable Groundwater Management Act analysis.\n\n# About\n\nIn 2014, California passed the Sustainable Groundwater Management Act (SGMA) aimed at addressing the over-exploitation of groundwater across California (Water Education Foundation, n.d.). The need for groundwater regulation was made urgent by the severe California drought of 2012-2016. This act required local and regional agencies to develop and implement sustainable groundwater management plans. High and medium-priority basins in critical overdraft were required to submit and begin implementing management plans by January 2020, while the rest had until January 2022 (Water Education Foundation, n.d.).\n\nThis analysis uses a segmented regression model to evaluate whether groundwater level trends changed after SGMA implementation. The analysis examines water surface elevations from January 2012 through November 2025 for monitoring wells across California operated by the California Department of Water Resources.\n\n# Data limitation\n\nThe groundwater level data used in this analysis exhibits several features that affect the statistical analysis:\n\nSeasonality: Groundwater levels fluctuate seasonally, increasing during wet seasons and decreasing during dry periods. This could make it difficult to distinguish seasonal groundwater water depletion from over drafting.\n\nAutocorrelation not addressed: This analysis does not account for autocorrelation in the regression model. Groundwater levels depend on previous levels. This creates autocorrelation for our response variables. Therefore, groundwater level observations cannot be considered independent. This can affect the reliability of standard errors and significance tests.\n\nPolicy Intervention Variation: Not all wells were subject to the January 2020 SGMA Sustainable Groundwater Plan submission and implementation. Some wells had until January 2022 to start implementing their plan. Despite this, a single policy intervention date (January 2020) was used in order to make a single breakpoint for groundwater level observations over time.\n\n# References\n\nCalifornia Department of Water Resources. (November 1, 2025). Continuous Groundwater Level Measurements. California Natural Resources Agency Open Data Portal. Retrieved December 4, 2024, from https://data.cnra.ca.gov/dataset/continuous-groundwater-level-measurements\n\nCalifornia Department of Water Resources. (November 1, 2025). Groundwater Sustainability Agencies. Retrieved December 4, 2024, from https://water.ca.gov/Programs/Groundwater-Management/SGMA-Groundwater-Management/Groundwater-Sustainable-Agencies\n\nWater Education Foundation. (n.d.). Sustainable Groundwater Management Act (SGMA). Aquapedia. Retrieved December 4, 2024, from https://www.watereducation.org/aquapedia-background/sustainable-groundwater-management-act-sgma\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in libraries\nlibrary(segmented)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: MASS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: nlme\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::collapse() masks nlme::collapse()\n✖ dplyr::filter()   masks stats::filter()\n✖ dplyr::lag()      masks stats::lag()\n✖ dplyr::select()   masks MASS::select()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(here)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nhere() starts at /Users/richardmonteslemus/Documents/git/personal/richardmonteslemus.github.io\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(lubridate)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in groundwater level data \ngw_level_month <- read_csv(here(\"posts\", \"cal_sgma_analysis\", \"data\", \"16f256f8-35a4-4cab-ae02-399a2914c282.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 100508 Columns: 13\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr   (1): STATION\ndbl  (11): _id, WLM_RPE, WLM_RPE_QC, WLM_GSE, WLM_GSE_QC, RPE_WSE, RPE_WSE_Q...\ndttm  (1): MSMT_DATE\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Read in groundwater station metadata\nstation <- read_csv((here(\"posts\", \"cal_sgma_analysis\", \"data\", \"03967113-1556-4100-af2c-b16a4d41b9d0.csv\")))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 733 Columns: 21\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (16): STATION, SITE_CODE, STNAME, WELL_NAME, LLDATUM, POSACC, ELEVDATUM,...\ndbl  (5): _id, LATITUDE, LONGITUDE, ELEV, WELL_DEPTH\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n# Cleaning data\n\nThe following code is used to generate a final data frame with information about each well's water surface elevation and station metadata. It transforms the time column from a string type to a date type to facilitate exploratory analysis plotting. Lastly, it removes problematic well measurements based on quality codes. It only keeps rows with quality codes 1 (good data), 2 (Good quality edited data), 10 (Good measurement), 15 (Provisional measurement).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join station and water level data \nstation_gw <- left_join(gw_level_month, station, by = \"STATION\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Turn time column into datetime type\nstation_gw <- station_gw %>% \n  mutate (\"MSMT_DATE\" = ymd(station_gw$MSMT_DATE)) %>% \n  filter(MSMT_DATE >= ymd(\"2012-01-01\")) # Select  measurements from 2012 and on \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Final quality filtering\nquality_codes_to_keep <- c(1, 2, 10, 15)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Return dataframe with high quality groundwater level measurements\nstation_gw_filtered <- station_gw %>%\n  filter(WSE_QC %in% quality_codes_to_keep) %>%\n  filter(!is.na(WSE))  # Remove missing water surface elevations\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot water surface elevation over time\nstation_gw_filtered %>% \nggplot(aes(x = MSMT_DATE, y = WSE)) + \n  geom_point() + \n  labs(\n    title = \"Observed Groundwater Levels in California\",\n    x = \"Date\",\n    y = \"Mean Water Surface Elevation (feet)\",\n    caption = \"Points = observed monthly averages\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 12, face = \"bold\"),\n  )\n```\n\n::: {.cell-output-display}\n![](Cal_SGMA_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe following code plots the observed groundwater water surface elevation. Visually it seems there is a significant increase in groundwater water surface elevation after 2020.\n\n# Prepare data for segmented regression model\n\nThe following code calculates the monthly mean groundwater level across all wells and creates a time counter variable, a variable needed for the segmentation regression analysis. The counter starts at 0 for January 2012 and increases by 1 for each following month. The code also obtains the counter number for January 2020 (SGMA implementation), which will be used as an initial estimate for the breakpoint in the segmented regression model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate monthly average across all wells\nstation_month_avg <- station_gw_filtered %>%\n  group_by(MSMT_DATE) %>%\n  summarize(mean_WSE = mean(WSE, na.rm = TRUE),\n            n_wells = n()) %>%\n  ungroup() %>% \n  arrange(MSMT_DATE) %>% # arrange by date \n  mutate(Time = 0:(n()-1)) # Add monthly counter \n\n# Find monthly counter number for policy implementation date\njan_2020_time <- min(station_month_avg$Time[station_month_avg$MSMT_DATE >= ymd(\"2020-01-01\")])\n```\n:::\n\n\n# Segmentation model\n\nFit a segmented regression model to the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit prerequisite linear model\ninitial_model <- lm(mean_WSE ~ Time, data = station_month_avg)\n\n# Fit segmented regression\nsgma_segmented <- segmented(initial_model, \n                            seg.Z = ~Time,\n                            psi = jan_2020_time)  # Initial guess\n\nsummary(sgma_segmented)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t***Regression Model with Segmented Relationship(s)***\n\nCall: \nsegmented.lm(obj = initial_model, seg.Z = ~Time, psi = jan_2020_time)\n\nEstimated Break-Point(s):\n              Est. St.Err\npsi1.Time 126.864  1.534\n\nCoefficients of the linear terms:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 249.2943     8.7450  28.507   <2e-16 ***\nTime          0.3121     0.1200   2.602   0.0101 *  \nU1.Time      11.7201     0.7154  16.384       NA    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 49.57 on 162 degrees of freedom\nMultiple R-Squared: 0.8672,  Adjusted R-squared: 0.8648 \n\nBoot restarting based on 6 samples. Last fit:\nConvergence attained in 2 iterations (rel. change 6.0253e-14)\n```\n\n\n:::\n:::\n\n\n# Interpret model results\n\nA segmented regression model was fitted to monthly groundwater water surface elevation measurements from January 2012 - November 2024. The model found the breakpoint to be month 126.86 which corresponds to approximately September 2022. This is about 2.5 years later than the expected breakpoint of January 2020. While it is possible that this is due to the implementation of groundwater management plans taking a while to impact groundwater levels, it is more probable that this breakpoint is attributed to extreme weather events. Around September 2022, California experienced extreme precipitation events that replenished groundwater levels all over the state. Therefore, it is difficult to make a distinction between extreme precipitation helping and SGMA plans affecting groundater levels.\n\n**Coefficients:**\n\nTime: 0.3121 feet/month This coefficient corresponds to the pre-breakpoint slope. On average, before the breakpoint, groundwater levels increased by about 0.3121 feet per month. This positive slope is likely due to the 2012 - 2016 California drought causing a low initial groundwater level. It is statistically significant with a p value of 0.0101.\n\nU1.Time: 11.7201 feet/month This coefficient corresponds to the post-breakpoint slope. On average, after the breakpoint, groundwater levels increased by about 11.7201 feet per month. This steep increase in slope is likely due to extreme precipitation events that occurred after the breakpoint. The model was unable to calculate a p value for this slope.\n\n**Model Fit:** R\\^2 = 0.8648\n\nThis model explains about 86.7% of the variability in groundwater levels during selected dates. This indicated a strong model fit.\n\n**Breakpoint:** The model calculated the breakpoint to be month 126.86 which is approximately September 2022.\n\n**Confidence Interval:** Time: 0.12 feet/month The standard error corresponds to the pre-breakpoint slope. We are 95% confident the slope is between 0.07 and 0.55 feet per month. Since zero is not included, we are confident groundwater levels were rising before the breakpoint.\n\nU1.Time: 0.72 feet/month The standard error corresponds to the post-breakpoint slope. Since we did not receive a P value for this slope we are unable to make claims about the confidence in the slope range.\n\nBreakpoint: 1.534 months The standard error corresponds to the breakpoint estimate. We are 95% confident the breakpoint falls between month 124 - 130 (July 2022 - November 2022).\n\n# Generate predicitons\n\nCreate a grid of predictions to input into model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create grid of predictions for entire time range \npred_grid <- expand_grid(\n  Time = seq(0, max(station_month_avg$Time), by = 1)  # Have every month from 0 to end \n)\n\n# Generate predictions using model and grid\nsegmented_predictions <- pred_grid %>%\n  mutate(\n    predicted_WSE = predict(sgma_segmented, newdata = pred_grid),\n    MSMT_DATE = min(station_month_avg$MSMT_DATE) + months(Time), # Add date \n    period = ifelse(Time < sgma_segmented$psi[2], \"Pre-breakpoint\", \"Post-breakpoint\") # Set pre and post breakpoint categories\n  )\n\n# Assign predicted breakpoint \nbreakpoint_date <- ymd(\"2022-09-01\")\n```\n:::\n\n\n# Plot predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot observed data and predicted segmented regression lines\nggplot() +\n  geom_point(data = station_month_avg, \n             aes(x = MSMT_DATE, y = mean_WSE),\n             alpha = 0.5, size = 2, color = \"gray40\") +\n  # Plot predicted segmented regression line\n  geom_line(data = segmented_predictions,\n            aes(x = MSMT_DATE, y = predicted_WSE, color = period)) +\n  # Vertical line at model breakpoint\n  geom_vline(xintercept = breakpoint_date,\n             linetype = \"dashed\", color = \"red\", size = 1) +\n  # Vertical line at SGMA implementation\n  geom_vline(xintercept = ymd(\"2020-01-01\"),\n             linetype = \"dotted\", color = \"darkgreen\", size = 1) +\n  annotate(\"text\", \n           x = breakpoint_date,\n           y = 750,\n           label = \"Model-estimated\\nbreakpoint\\n(Sept 2022)\",\n           color = \"red\", hjust = -0.1, size = 2) +\n  annotate(\"text\",\n           x = ymd(\"2020-01-01\"),\n           y = 200,\n           label = \"SGMA\\nimplementation\\n(Jan 2020)\",\n           color = \"darkgreen\", hjust = 1.1, size = 2) +\n  scale_color_manual(values = c(\"Pre-breakpoint\" = \"cornflowerblue\", \n                                  \"Post-breakpoint\" = \"firebrick\"),\n                     name = \"Time Period\") +\n  labs(\n    title = \"Segmented Regression Model: Observed vs. Predicted Groundwater Levels in California\",\n    x = \"Date\",\n    y = \"Mean Water Surface Elevation (feet)\",\n    caption = \"Points = observed monthly averages; Lines = segmented regression predictions\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 11, face = \"bold\"),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Cal_SGMA_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe following code plots the observed and predicted groundwater water surface elevation. Visually, it seems that the slopes predicted by the segmentation regression fit the observed data well.\n",
    "supporting": [
      "Cal_SGMA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}